### ISSUE TITLE
Consider supporting occur searches

### ISSUE THREAD

**Issue by nowislewis** [emacs-eaf/eaf-pdf-viewer#104]
**Describe the solution you'd like**
I wonder if EAF has a way to support occur-mode. The use cases are as follows: EAF already supports incremental search similar to iSearch, which is fast and has a good experience, but it takes a jump forward to know if it is the search place you need.

 Sometimes we may prefer to choose from a series of search results (such as Blink-Search or Consult does).

**Describe alternatives you've considered**
Pdf-tools does a similar job:
For example, when I wanted to know how to measure performance, so I searched "measure performance", I got a list of results, and I could jump back and forth at will with follow-mode on the right.
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/41566630/236594372-ffe2caed-3c9f-4443-985e-f646d0b6671c.png">

And I think this one is useful not only for reading pdfs, but also for eaf-browsers(such as occur on current page) etc, we could get a global-view and just pick someone.

Thanks for the wonderful eaf-project!
Season's greetings.

**Comment by manateelazycat** [comment]
blink-search has SearchGrepPDF backend https://github.com/manateelazycat/blink-search/blob/f9d7e573ea9069dcfbf11cf869dbf6e598d7068a/backend/search_grep_pdf.py#L8

It base on rga.

**Comment by manateelazycat** [comment]
Or another solution:

1. Write new function that same as search_text https://github.com/emacs-eaf/eaf-pdf-viewer/blob/21a3b16765fac799b52e57b6af2f6e49a5cf72ce/eaf_pdf_widget.py#L1015 to got list like search_text_quads_list
2. Then write new elisp plugin that like https://github.com/manateelazycat/lsp-bridge/blob/8e7103e50bb04290d40e1d70e2bfeaa5dd48b594/lsp-bridge-ref.el#L1
3. Pass search_text_quads_list data to list of step 2
4. When cursor move in ui of step 2, jump to special postion inf eaf-pdf-viewer.

**Comment by nowislewis** [comment]
Yes, I'm using this, and I've been using rga in blink-search for a long time (since I switched to eaf-pdf-viewer). 

Blink-search with rga is very suitable for the following situation: when we need to query a certain aspect of information, we can search all relevant documents through rga, simply browse the context on Blink-search and then jump to a certain data to view.

But for my long-term use, it's not very convenient and lacks some useful ideas. And then I often have to reopen the PDF file with pdf-tools.

**Comment by manateelazycat** [comment]
> Or another solution:
> 
> 1. Write new function that same as search_text https://github.com/emacs-eaf/eaf-pdf-viewer/blob/21a3b16765fac799b52e57b6af2f6e49a5cf72ce/eaf_pdf_widget.py#L1015
>     to got list like search_text_quads_list
> 2. Then write new elisp plugin that like https://github.com/manateelazycat/lsp-bridge/blob/8e7103e50bb04290d40e1d70e2bfeaa5dd48b594/lsp-bridge-ref.el#L1
> 3. Pass search_text_quads_list data to list of step 2
> 4. When cursor move in ui of step 2, jump to special postion inf eaf-pdf-viewer.

@nowislewis This is what you need, PR are welcome, I'm too busy recently.

**Comment by nowislewis** [comment]
@manateelazycat  Great! I'll try it.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/blink-search/commit/0d3f086aa675c543581837b731700b0d7e569a02

blink-search 实现了针对当前 pdf buffer 的 occur 功能， 直接更新 blink-search 就好了。

![截图 2023-05-31 10-40-31](https://github.com/emacs-eaf/eaf-pdf-viewer/assets/237487/3fb1f383-7fd7-4863-bc70-6a109bee4e95)
