### ISSUE TITLE
The PDF viewer doesn't seem to be able to handle mouse events at high speed

### ISSUE THREAD

**Issue by ChillingHsu** [emacs-eaf/eaf-pdf-viewer#12]
**Describe the bug**
The visual response lags a bit when I try to select parts of the text

**To Reproduce**
Repeated selection of parts of the text (if you combine scrolling with selection, this problem becomes more apparent).

**Expected behavior**
The visual response becomes more smoothly, just like in the Okular.

**Versions (please complete the following info):**
 - Distro and DE/WM: Arch / KDE
 - Versions of Dependencies:
   - PyQt5                  5.15.4
   - PyQtWebEngine          5.15.4 
   - PyMuPDF 1.18.17
 - M-x emacs-version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4)

**Screenshots**
NA

**Comment by luhuaei** [comment]
I try to optimize it

**Comment by luhuaei** [comment]
> paintEvent 函数中绘制选中区域的代码效率不够高，当MouseMove事件触发 update 信号后，因为每次绘制选中区域的代码比较慢，连续移动鼠标会给用户卡顿的感觉。

看了下找不到主要的瓶颈，主要是这个不知道怎个测试，在我电脑上，`okular` 和 `eaf-pdf` 的差别不是很大 :joy: 。

- `eaf-pdf` 计算选中的区域， 主要是通过选中文字的`rect` 来组合成一个异形的区域。
- `eaf-pdf` 里面是使用 `annot` 来绘制高亮的， 每发生变化都会重新清理掉原来的`pixmap`缓存，获取新的`pixmap`图片。

**Comment by manateelazycat** [comment]
> > paintEvent 函数中绘制选中区域的代码效率不够高，当MouseMove事件触发 update 信号后，因为每次绘制选中区域的代码比较慢，连续移动鼠标会给用户卡顿的感觉。
> 
> 看了下找不到主要的瓶颈，主要是这个不知道怎个测试，在我电脑上，`okular` 和 `eaf-pdf` 的差别不是很大 😂 。
> 
> * `eaf-pdf` 计算选中的区域， 主要是通过选中文字的`rect` 来组合成一个异形的区域。这个其实已经作了一部分处理，在加载`page`的时候，已经将整个`page`的`text`都进行初始化了的
> * `eaf-pdf` 里面是使用 `annot` 来绘制高亮的， 每发生变化都会重新清理掉原来的`pixmap`缓存，获取新的`pixmap`图片。 这个目前不知道怎么改，或许可以改成使用`qt`来绘制高亮的区域 🤔

qt画的话，滚动的时候要处理好

**Comment by manateelazycat** [comment]
> > paintEvent 函数中绘制选中区域的代码效率不够高，当MouseMove事件触发 update 信号后，因为每次绘制选中区域的代码比较慢，连续移动鼠标会给用户卡顿的感觉。
> 
> 看了下找不到主要的瓶颈，主要是这个不知道怎个测试，在我电脑上，`okular` 和 `eaf-pdf` 的差别不是很大 joy 。
> 
> * `eaf-pdf` 计算选中的区域， 主要是通过选中文字的`rect` 来组合成一个异形的区域。这个其实已经作了一部分处理，在加载`page`的时候，已经将整个`page`的`text`都进行初始化了的
> * `eaf-pdf` 里面是使用 `annot` 来绘制高亮的， 每发生变化都会重新清理掉原来的`pixmap`缓存，获取新的`pixmap`图片。 这个目前不知道怎么改，或许可以改成使用`qt`来绘制高亮的区域 thinking

这个问题卡主要在于每次都要重新绘制 pixmap, 这个太耗时了，建议不要管 pixmap, 用Qt在 *顶部* 绘制图形层表示选中区域，这样就会卡顿了。

**Comment by luhuaei** [comment]
> > > paintEvent 函数中绘制选中区域的代码效率不够高，当MouseMove事件触发 update 信号后，因为每次绘制选中区域的代码比较慢，连续移动鼠标会给用户卡顿的感觉。
> > 
> > 
> > 看了下找不到主要的瓶颈，主要是这个不知道怎个测试，在我电脑上，`okular` 和 `eaf-pdf` 的差别不是很大 joy 。
> > 
> > * `eaf-pdf` 计算选中的区域， 主要是通过选中文字的`rect` 来组合成一个异形的区域。这个其实已经作了一部分处理，在加载`page`的时候，已经将整个`page`的`text`都进行初始化了的
> > * `eaf-pdf` 里面是使用 `annot` 来绘制高亮的， 每发生变化都会重新清理掉原来的`pixmap`缓存，获取新的`pixmap`图片。 这个目前不知道怎么改，或许可以改成使用`qt`来绘制高亮的区域 thinking
> 
> 这个问题卡主要在于每次都要重新绘制 pixmap, 这个太耗时了，建议不要管 pixmap, 用Qt在 _顶部_ 绘制图形层表示选中区域，这样就会卡顿了。

嗯，我先试试, 通过mupdf可以得到每一个字符的rect，通过这些rect可以拼出一个表示选中的图形层出来

**Comment by manateelazycat** [comment]
fixed by https://github.com/emacs-eaf/eaf-pdf-viewer/pull/57#event-5899572576
