### ISSUE TITLE
选中区域后区域里的内容消失

### ISSUE THREAD

**Issue by Thysrael** [emacs-eaf/eaf-pdf-viewer#123]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.

`*eaf*` 中没有任何信息

**Describe the bug**
用鼠标选中区域后，区域会消失，如图所示：

![test](https://github.com/emacs-eaf/eaf-pdf-viewer/assets/72613958/1def58bb-6354-42b6-8ea2-5d94d086c928)

**To Reproduce**
如图所示

**Expected behavior**
区域不消失

**Versions (please complete the following info):**
 - Distro and DE/WM: Manjaro 23.1.2
 - Versions of Dependencies:
 - M-x emacs-version: 29.1

配置如下

```emacs-lisp
(use-package eaf-pdf-viewer
  :straight nil
  :init
  (require 'eaf-pdf-viewer)
  (setq eaf-pdf-dark-mode nil)
  )
```

**Additional context**
测试的 pdf 是 https://web.mit.edu/~simsong/www/ugh.pdf

**Comment by manateelazycat** [comment]
黑色主题没有这个问题， 白色主题下有这个bug

**Comment by manateelazycat** [comment]
我看了一下没头绪， 要等 @luhuaei 有空看看， 他更熟悉这部分代码

**Comment by manateelazycat** [comment]
最新版已经修复

**Comment by Thysrael** [comment]
我更新了 eaf 和 eaf-pdf-viewer，依然存在这样的问题。请问还可以怎样排查呀？

**Comment by Thysrael** [comment]
我测试使用这个 PDF ()[http://cjc.ict.ac.cn/online/onlinepaper/zxy-20175683124.pdf]

消失的效果如图所示：

中文 PDF：

![Peek 2024-05-17 18-45](https://github.com/emacs-eaf/eaf-pdf-viewer/assets/72613958/e769e5f7-ba81-453b-a8ed-ed19cfeb9844)

英文 PDF：

![Peek 2024-05-17 18-48](https://github.com/emacs-eaf/eaf-pdf-viewer/assets/72613958/faabeb47-af0a-4963-a585-24efe2d4df62)

使用的主题是 `doom-dracula` ，`emacs -Q` 也能复现。

**Comment by manateelazycat** [comment]
你换个主题呢， 我刚刚没重现

**Comment by Thysrael** [comment]
不使用主题也会出现这个问题

![Peek 2024-05-17 19-35](https://github.com/emacs-eaf/eaf-pdf-viewer/assets/72613958/276f52ec-0857-4322-9e98-7bff71f8e206)

另外我注意到如果我使用 pdf 的黑色模式，那么也会出现问题：

![Peek 2024-05-17 19-39](https://github.com/emacs-eaf/eaf-pdf-viewer/assets/72613958/11f5af8f-96eb-49ea-ac0d-b4a197b0782c)

表现就是整个 buffer 没有反应，而且 vertico 这种会占据 buffer 空间的东西也会被盖住，`*eaf*` 中也没有输出。

**Comment by manateelazycat** [comment]
我的CPU也是狂飙的， 不知道是不是升级了什么导致的。

**Comment by manateelazycat** [comment]
@luhuaei 感觉最新版是不是哪里无限循环了， 整个EAF都卡住了， 你那里能重现吗？

**Comment by manateelazycat** [comment]
我发现 eaf-pdf-viewer 进入 invert mode 的时候， CPU很高， 浅色模式的时候是正常的

**Comment by manateelazycat** [comment]
找到地方了， eaf-pdf-viewer 代码没有动， 但是 pymupdf 升级后

https://github.com/emacs-eaf/eaf-pdf-viewer/blob/0b79e9000551200b6a0d2206de14b87d9ed3c9c9/eaf_pdf_page.py#L198

这一行代码的性能特别特别差

**Comment by manateelazycat** [comment]
我提交了一个 issue https://github.com/pymupdf/PyMuPDF/issues/3498

**Comment by manateelazycat** [comment]
你暂时用 (setq eaf-pdf-dark-mode "ignore") 来规避性能问题吧 @Thysrael

**Comment by Thysrael** [comment]
哇，太感谢了。不过请问“选中区域消失”这个问题还有办法继续排查吗？似乎不更新的时候也有这个问题。

**Comment by manateelazycat** [comment]
> 哇，太感谢了。不过请问“选中区域消失”这个问题还有办法继续排查吗？似乎不更新的时候也有这个问题。

选中区域我在补丁 https://github.com/emacs-eaf/eaf-pdf-viewer/commit/ea467c4fed134b30d5b11a6b83900bd3bb87dc32 已经修复了， 我本地无法重现， 你看看这个补丁的地方， 你看看强制改改是否生效？

**Comment by Thysrael** [comment]
我查看了一下这个补丁所在的函数

```python
    def mark_select_char_area(self, page_index, pixmap):
        def quad_to_qrect(quad):
            qrect = quad.rect * self.scale * self.devicePixelRatioF()
            rect = QRect(int(qrect.x0), int(qrect.y0), int(qrect.width), int(qrect.height))
            return rect

        qp = QPainter(pixmap)
        qp.setRenderHint(QPainter.RenderHint.Antialiasing)
        qp.setCompositionMode(QPainter.CompositionMode.CompositionMode_SourceAtop)
        qp.save()

        # clear old highlight
        if page_index in self.select_area_annot_quad_cache_dict:
            old_quads = self.select_area_annot_quad_cache_dict[page_index]
            foreground_color = "#000000" if self.inverted_mode else "#FFFFFF"
            for quad in old_quads:
                qp.fillRect(quad_to_qrect(quad), foreground_color)

        # update select area quad list
        self.update_select_char_area()

        # draw new highlight
        if page_index in self.select_area_annot_quad_cache_dict:
            quads = self.select_area_annot_quad_cache_dict[page_index]
            for quad in quads:
                qp.fillRect(quad_to_qrect(quad), QColor(self.text_highlight_annot_color))

        qp.restore()
        return pixmap
```

我不懂 QT，所以想请教您，我从手册中查到，`fillRect` 的原型是这个

```c++
oid QPainter::fillRect(const QRect &rectangle,, const QColor &color)
```

意思是不是说将这个矩形的颜色填充特定的颜色？那么在代码中，将整个矩形填充成 `#000000` 白色是正确的吗？这个操作用于取消高亮，那么效果应该是白底黑字（白色模式）。但是这样写似乎会导致白底白字。

另外如果希望选中区域出现空白，需要一直按住鼠标的左键滑动，并且需要左右移动重复覆盖，才可以复现问题。

**Comment by zhenhua-wang** [comment]
> 我发现 eaf-pdf-viewer 进入 invert mode 的时候， CPU很高， 浅色模式的时候是正常的

> 不过请问“选中区域消失”这个问题还有办法继续排查吗？似乎不更新的时候也有这个问题。

我发现这俩问题都与pymupdf版本有关。换成这个pymupdf==1.21.0版本后这俩问题都解决了。。。

**Comment by manateelazycat** [comment]
> 我查看了一下这个补丁所在的函数
> 
> ```python
>     def mark_select_char_area(self, page_index, pixmap):
>         def quad_to_qrect(quad):
>             qrect = quad.rect * self.scale * self.devicePixelRatioF()
>             rect = QRect(int(qrect.x0), int(qrect.y0), int(qrect.width), int(qrect.height))
>             return rect
> 
>         qp = QPainter(pixmap)
>         qp.setRenderHint(QPainter.RenderHint.Antialiasing)
>         qp.setCompositionMode(QPainter.CompositionMode.CompositionMode_SourceAtop)
>         qp.save()
> 
>         # clear old highlight
>         if page_index in self.select_area_annot_quad_cache_dict:
>             old_quads = self.select_area_annot_quad_cache_dict[page_index]
>             foreground_color = "#000000" if self.inverted_mode else "#FFFFFF"
>             for quad in old_quads:
>                 qp.fillRect(quad_to_qrect(quad), foreground_color)
> 
>         # update select area quad list
>         self.update_select_char_area()
> 
>         # draw new highlight
>         if page_index in self.select_area_annot_quad_cache_dict:
>             quads = self.select_area_annot_quad_cache_dict[page_index]
>             for quad in quads:
>                 qp.fillRect(quad_to_qrect(quad), QColor(self.text_highlight_annot_color))
> 
>         qp.restore()
>         return pixmap
> ```
> 
> 我不懂 QT，所以想请教您，我从手册中查到，`fillRect` 的原型是这个
> 
> ```c++
> void QPainter::fillRect(const QRect &rectangle,, const QColor &color)
> ```
> 
> 意思是不是说将这个矩形的颜色填充特定的颜色？那么在代码中，将整个矩形填充成白色是正确的吗？这个操作用于取消高亮，那么效果应该是白底黑字（白色模式）。但是这样写似乎会导致白底白字。
> 
> 另外如果希望选中区域出现空白，需要一直按住鼠标的左键滑动，并且需要左右移动重复覆盖，才可以复现问题。

fillRect 只是绘制背景， 要看 fillRect 的颜色和后续的 drawText （绘制文字）的颜色是否是一样的？

我感觉这个是某些主题导致背景色和前景色一样的问题， 我这边重现不了
