### ISSUE TITLE
How to make Emacs stay in LaTeX buffer after doing a sync-tex-backward-edit from EAF pdf-viewer?

### ISSUE THREAD

**Issue by taquangtrung** [emacs-eaf/eaf-pdf-viewer#13]
Hi,

**Is your feature request related to a problem? Please describe.**

When I use EAF pdf-viewer to open a PDF file generated by LaTeX, and double-click on the PDF file, I see that EAF pdf-viewer can synchronize backward to the corresponding LaTeX buffer: it opens the LaTeX buffer and locate to the corresponding line of LaTeX source code.

However, after Emacs jumps to the LaTeX buffer, it immediately jumps back to the EAF pdf-viewer buffer.

**Describe the solution you'd like**

Is there a way to make Emacs stays in the LaTeX buffer?

**Describe alternatives you've considered**

I looked into the code of `buffer.py` in EAF pdf-viewer and see that the function below is called:

```python
eval_in_emacs("eaf-pdf-synctex-backward-edit", [self.url, page_index + 1, ex, ey])
```

and `eaf-pdf-synctex-backward-edit` does select the buffer correctly.

However, I don't know why after executing `eval_in_emacs`, the EAF pdf-viewer window is selected again.

**Comment by manateelazycat** [comment]
@xhcoding Any idea?

**Comment by taquangtrung** [comment]
@manateelazycat: I closed this issue since it was fixed by https://github.com/emacs-eaf/eaf-pdf-viewer/pull/17
