### ISSUE TITLE
批注后再打开pdf文件时显示"Failed to reload PDF"

### ISSUE THREAD

**Issue by hitswint** [emacs-eaf/eaf-pdf-viewer#131]
**Describe the bug**
minibuffer区域始终重复显示"Failed to reload PDF"

**To Reproduce**
打开pdf文件并做批注，然后关闭pdf后再重新打开pdf，到这时候都是正常的。然后，再次做批注的时候，就会出现"Failed to reload PDF"的提示。另外，批注后关闭pdf，不再打开，此时如果使用其他工具修改pdf文件，例如office重新导出相同的pdf文件，仍然不断弹出相同的错误提示。

**Versions (please complete the following info):**
 - Debian 12，dwm:
 - Emacs 29.3:

**Comment by manateelazycat** [comment]
@hitswint 我写了一个补丁， 应该不会一直提示错误提示了， 不确定是否从根源修好了， 因为 EAF pdf viewer 已经复杂到超出我的使用范围了。

**Comment by hitswint** [comment]
> @hitswint 我写了一个补丁， 应该不会一直提示错误提示了， 不确定是否从根源修好了， 因为 EAF pdf viewer 已经复杂到超出我的使用范围了。

\*eaf\*中还是会出现"Failed to reload PDF"的提示，但是不影响使用了，可以不用纠结这个问题了

**Comment by manateelazycat** [comment]
> > @hitswint 我写了一个补丁， 应该不会一直提示错误提示了， 不确定是否从根源修好了， 因为 EAF pdf viewer 已经复杂到超出我的使用范围了。
> 
> *eaf*中偶尔还是会出现"Failed to reload PDF"的提示，但是不影响使用了，可以不用纠结这个问题了

这个reload是为哪些LaTeX用户， 修改 LaTeX 后自动生成 PDF 文件设计的。

只是感觉标注以后， PDF文件会变动也会触发重新加载， 如果要去除这个提示， 要看看刚刚是否是做了标注操作导致的PDF内容变化。
