### ISSUE TITLE
Support undo/redo actions

### ISSUE THREAD

**Issue by taquangtrung** [emacs-eaf/eaf-pdf-viewer#25]
Hi,

**Is your feature request related to a problem? Please describe.**

Currently, if I accidentally delete a note, there is no feature to undo my action, hence I cannot recover the note.

**Describe the solution you'd like**

It would be nice if EAF pdf-viewer can support undo/redo action.

(However, I think it is quite challenging to implement as we need to maintain a state of action sequences)

**Comment by manateelazycat** [comment]
PR are welcome, I believe you can do this. ;)

**Comment by taquangtrung** [comment]
@manateelazycat : it's quite challenging though, as we need a mechanism to capture the sequence of editing/annotating actions and document states.

I'll take a look when I have some time :D

**Comment by manateelazycat** [comment]
I think you just need build a list to contain actions, undo is remove last element from list

**Comment by taquangtrung** [comment]
@manateelazycat : I check the documentation of Page (https://pymupdf.readthedocs.io/en/latest/page.html) and there is NO function to add a general annot like `addAnnot(...)`. It only supports functions to add specific an annot like `add_caret_annot, add_highlight_annot`

We can implement `undo` by calling to `deleteAnnot(annot)`.

But I'm not sure how to implement `redo` to add an annot which is deleted previously.

Do you have any suggestion?

**Comment by manateelazycat** [comment]
> @manateelazycat : I check the documentation of Page (https://pymupdf.readthedocs.io/en/latest/page.html) and there is NO function to add a general annot like `addAnnot(...)`. It only supports functions to add specific an annot like `add_caret_annot, add_highlight_annot`
> 
> We can implement `undo` by calling to `deleteAnnot(annot)`.
> 
> But I'm not sure how to implement `redo` to add an annot which is deleted previously.
> 
> Do you have any suggestion?

Build a new annot class and include annot type, you can record type of deleted annot, then use Page.add_*_annot functions.

**Comment by taquangtrung** [comment]
Thanks! That is quite manual, but I think we do not have many options. I'll try to implement it.
