### ISSUE TITLE
Pdf viewer: support two-ways synctex integration

### ISSUE THREAD

**Issue by antoine-levitt** [emacs-eaf/eaf-pdf-viewer#4]
Hi and congratulations for this amazing package, I'm blown away. The pdf viewer is great, but I'm missing synctex integration. This is in two parts: first, jump from a latex buffer to the position in the pdf, and second jump from a pdf to the latex buffer

**Comment by MatthewZMD** [comment]
Should hopefully be fixed in the latest PDF-viewer
