### ISSUE TITLE
Black background of pdf file in the white theme

### ISSUE THREAD

**Issue by duzaichuan** [emacs-eaf/eaf-pdf-viewer#47]
Up-to-date EAF and dependencies installed
Manjaro kde
Emacs 28.06
*eaf* : 
`Deprecation: 'pageCropBox' removed from class 'Document' after v1.19.0 - use 'page_cropbox'.
Deprecation: 'setCropBox' removed from class 'Page' after v1.19.0 - use 'set_cropbox'.
Deprecation: 'getText' removed from class 'Page' after v1.19.0 - use 'get_text'.
Deprecation: 'setRotation' removed from class 'Page' after v1.19.0 - use 'set_rotation'.
Deprecation: 'getPixmap' removed from class 'Page' after v1.19.0 - use 'get_pixmap'.
`

As the title says, how can I change the black bg to be consistent with my light theme? Thank you!

**Screenshots**
![image](https://user-images.githubusercontent.com/32022901/139533644-4bcedfe4-d727-4dd7-9f0c-cabc6e5573ea.png)

**Comment by manateelazycat** [comment]
Try (eaf-setq eaf-buffer-background-color "#FF0000")

**Comment by duzaichuan** [comment]
Worked. Many thanks.

**Comment by MatthewZMD** [comment]
Actually, eaf-setq is unnecessary now, just use setq
