### ISSUE TITLE
Can Pdf-viewer display a tool tip over the Pdf page to indicate the synchronized text?

### ISSUE THREAD

**Issue by taquangtrung** [emacs-eaf/eaf-pdf-viewer#6]
Hi,

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I'm using the feature that synchronizes from LaTeX file to PDF file (nice feature btw), and think that it would be very useful if Pdf-viewer can display a tooltip over the Pdf page to indicate the corresponding parts between Pdf and LaTeX files.

This feature is currently supported by pdf-tools: https://github.com/politza/pdf-tools/blob/c510442ab89c8a9e9881230eeb364f4663f59e76/lisp/pdf-sync.el#L675

Here is the screenshot of pdf-tools:

![pdftool](https://user-images.githubusercontent.com/193967/130441117-1d8121e2-c951-4953-b0e7-932cef1c674e.png)

It would be very nice if EAF Pdf-viewer can support it too.

**Describe alternatives you've considered**

I tried to bring the code from pdf-tools over EAF Pdf-viewer but wasn't successful.

**Comment by manateelazycat** [comment]
@xhcoding It's is possible?

**Comment by xhcoding** [comment]
I don't know. I'll try it on the weekend

**Comment by c1-g** [comment]
This might be useful https://pymupdf.readthedocs.io/en/latest/faq.html#drawing-and-graphics
You can draw an arrow, a hand, a heart etc.
