### ISSUE TITLE
Following links in PDFs and epubs

### ISSUE THREAD

**Issue by Jdogzz** [emacs-eaf/eaf-pdf-viewer#62]
**Is your feature request related to a problem? Please describe.**
I've found that PDFs and epubs which contain links can't have the links followed when clicked in eaf-pdf-viewer. As examples, here are two documents which have this behavior for me:

PDF: [https://arxiv.org/abs/2002.01247](https://arxiv.org/abs/2002.01247)
This document has various links which can be clicked to navigate to parts of the PDF, like references at the end.

epub: [https://creativecommons.org/use-remix/made-with-cc/](https://creativecommons.org/use-remix/made-with-cc/)
This document has various links which can be clicked on to navigate to things like endnotes in the epub chapters.

I see there are keyboard shortcuts m and f related to links, but they don't seem to do be following links or enable clicking of links.

**Describe the solution you'd like**
Simply allow for a link to be clicked and followed.

**Describe alternatives you've considered**
None.

**Additional context**
Screenshot of the above PDF in eaf-pdf-viewer which has links:
![image](https://user-images.githubusercontent.com/2792697/155054471-d697cbb5-ab3e-4ab8-86a1-ebe40a3dbf56.png)

Screenshot of the above epub in eaf-pdf-viewer which has links:
![image](https://user-images.githubusercontent.com/2792697/155054552-7d0e9843-6c9b-4c84-8cdb-05a582fb2855.png)

**Comment by Jdogzz** [comment]
I can confirm that the (right) clicking successfully navigates the links. Should I leave this open until the m and f are supported so there's feature parity with PDFs? I do see their value compared to just the clicking now that I've had time to try them out.

**Comment by manateelazycat** [comment]
> I can confirm that the (right) clicking successfully navigates the links. Should I leave this open until the m and f are supported so there's feature parity with PDFs? I do see their value compared to just the clicking now that I've had time to try them out.

No, pymupdf just can render epub file, but not support all features to epub file like PDF does.

Thanks for report.
