### ISSUE TITLE
Single page viewing

### ISSUE THREAD

**Issue by strow** [emacs-eaf/eaf-pdf-viewer#64]
Very fast and very nice viewer.  But, wondering if a new feature is possible, since it makes, in my opinion, viewing a pdf presentation much easier.

I would like to force EOF to only show 1 page in the pdf file at a time, and then have a keystrokes that let you move up 1 page, or down 1 page.   Right now the "page" movement slowly shifts such that you are looking in the middle of pages.

Thanks!

**Comment by MatthewZMD** [comment]
It is already implemented, press `M-p` to enter presentation mode.

**Comment by strow** [comment]
OK, I tried that previously.   I now see what the issue likely is.    I use
emacs in two column mode ("New Window on Right").  My text (orgmode on
latex) is on the left, the eaf rendering of the PDF file on the right, in a
somewhat bigger window (irrelevant).   When you use M-p in this mode, eaf
renders the page for the full emacs frame size, so it is too large in the
RHS window.   I've tried de-zooming the PDF size with eap, but then you are
back in the normal mode of not scrolling exactly 1 page.    I figured just
use a separate emacs frame for eap, but that doesn't work, I guess since
you are doing some very fancy overlaying onto the emacs emacs frame (it
just goes blank if you don't have focus on that frame, which I assume is
normal behavior).   I find this kind of setup is very very nice for
developing talks (using beamer).

I think I just will change "my behavior" if need be, and not require that I
see both the text and the eaf pdf rendering at the same time...

It does see that after you do (in one window) M-p, you have to use C-p and
C-n to scroll by one page up and down, SPC and b don't do anything after
M-p.   Fine, just thought I would mention it.

Just FYI, I had been using pdf-tools, but just can't get it to compile on
Mac OS, latest version.   Although I am an amatuer, I'm usually able to
mess with ./configure scripts to diagnose and fix missing stuff.  Couldn't
do it this time.  But, eaf is really really fast!

------------------------------------------
L. Larrabee Strow
UMBC Physics Department
Email: ***@***.***
Phone: 724-288-6933

**Comment by MatthewZMD** [comment]
> When you use M-p in this mode, eaf renders the page for the full emacs frame size, so it is too large in the RHS window. I've tried de-zooming the PDF size with eap, but then you are back in the normal mode of not scrolling exactly 1 page.

Let me get this straight, do you want to display only 1 slide even after zooming out in `M-p` presentation mode? This is not the current behavior.

Anyways, what you *can* do if you find the right window too large is to divide the window by half so the PDF rendering window's height is shorter, then set the bottom-right buffer to some empty scratch buffer to avoid distraction, and increase the height of the top-right buffer - your EAF PDF buffer in `M-p` presentation mode - to some height that you feel the rendering at the right size.



> SPC and b don't do anything after
M-p

You can use `j`/`k` to scroll up/down, or simply `(eaf-bind-key scroll_up "SPC" eaf-pdf-viewer-keybinding)` to re-bind SPC to `scroll_up`.

**Comment by MatthewZMD** [comment]
Let me demonstrate what I mean:

![DeepinScreenshot_select-area_20220224140513](https://user-images.githubusercontent.com/12422335/155590546-83856cf7-f26d-4597-96e6-5313401192ff.png)

**Comment by strow** [comment]
Thank you!   That's a nice work around!   And again, thanks for all your
work on eap!

------------------------------------------
L. Larrabee Strow
UMBC Physics Department
Email: ***@***.***
Phone: 724-288-6933
