### ISSUE TITLE
eaf-pdf-dark-mode do not display correct.

### ISSUE THREAD

**Issue by Jousimies** [emacs-eaf/eaf-pdf-viewer#66]
I use modus-themes, with white background for sunrise, and blackground for sunset.

Config related eaf-pdf-viewer:
```
(setq eaf-pdf-dark-mode "follow")
```

If current background is white, When I open a pdf file, the color do not display correct, I need to press key i to toggle inverted mode.
![Screenshot from 2022-03-08 15-02-41](https://user-images.githubusercontent.com/72933939/157184412-6083ffdc-3913-45bb-b180-e530c2fb27a5.png)

If I change theme to black background, `modus-themes-toggle', re-open the pdf file, the display was right.

If I set eaf-pdf-dark-mode to `force' , the display behavior same as `follow'.

**Comment by manateelazycat** [comment]
最近太忙，可能要周末才能有时间修复。

**Comment by manateelazycat** [comment]
@Jousimies 已经修复了，请更新EAF
