### ISSUE TITLE
Keep focus in TeX file after TeX-view

### ISSUE THREAD

**Issue by allenryb** [emacs-eaf/eaf-pdf-viewer#74]
I am using `eaf-pdf-viewer` and `auctex`.

After `TeX-view (C-c C-v)`, the focus switches from `tex` buffer to `PDF` buffer. 
Is it possible to keep focus on the `tex` buffer?

**Comment by manateelazycat** [comment]
Welcome to send PR

**Comment by allenryb** [comment]
I am not a developer and just use emacs to write TeX. 
So I am a freshman here and struggle to submit the first PR in my life. 

I have modified `eaf-pdf-synctex-forward-view` in [here](https://github.com/allenryb/eaf-pdf-viewer/commit/c97a8ce05baa29b577ce0ed52aef15bdcefce2a1)
Before submitting this PR, I want to ask whether `eaf-open` supports displaying with `other-window` action. 
If no, my idea is wrapping `eaf-open` by two `other-window`, 
See the following in [Line 603-609](https://github.com/allenryb/eaf-pdf-viewer/blob/c97a8ce05baa29b577ce0ed52aef15bdcefce2a1/eaf-pdf-viewer.el#L603-L609)

```
          (progn
	    ;; `eaf-open' shows PDF in currrent buffer
	    ;; Hence we have to swtich to other window
	    (other-window 1)
	    (eaf-open pdf-url "pdf-viewer" (format "synctex_info=%s" synctex-info))
	    ;; `eaf-open' break `with-current-buffer' and can't go back to source buffer
	    (other-window 1))
```

**Comment by manateelazycat** [comment]
@luhuaei Can you help me review this patch?

**Comment by allenryb** [comment]
When I take the first `eaf-pdf-synctex-forward-view` from a TeX file, `eaf-padf-viewer` only open the PDF file but no sync forward.
It seems a problem about `eaf-open`. I test the following 

```
(eaf-open pdf-url "pdf-viewer" (format "synctex_info=%s" "3:28.346443:113.003693"))
```

The variable `pdf-url` is obtained by `(setq (pdf-url (expand-file-name (TeX-active-master (TeX-output-extension)))))`
The synctex-info `3:28.346443:113.003693` is obtained by `(eaf--create-buffer pdf-url "pdf-viewer" (format "%s" synctex-info))`

**Comment by luhuaei** [comment]
@allenryb  谢谢你的补丁，但从我的测试结果看 https://github.com/allenryb/eaf-pdf-viewer/commit/c97a8ce05baa29b577ce0ed52aef15bdcefce2a1 第一次在一个 tex 文件中执行 `C-c C-v` 的时候是正常的，

如果将`pdf-viewer` buffer 关闭侯，再次在 tex 中执行 `C-c C-v` 会出现多个窗口。我稍微改了下，你可以试一下效果。https://github.com/luhuaei/eaf-pdf-viewer/commit/976b513ef488546d31389e15307da08a0f52fbbe

**Comment by allenryb** [comment]
谢谢～

**Comment by luhuaei** [comment]
我把这个推送到 master 分支了
