### ISSUE TITLE
getToC rename to get_toc in pymupdf-1.20.1

### ISSUE THREAD

**Issue by wcq062821** [emacs-eaf/eaf-pdf-viewer#77]
https://github.com/emacs-eaf/eaf-pdf-viewer/blob/8baeffd3261e86b65ea804a807463215267baabf/eaf_pdf_buffer.py#L292

**Comment by manateelazycat** [comment]
> https://github.com/emacs-eaf/eaf-pdf-viewer/blob/8baeffd3261e86b65ea804a807463215267baabf/eaf_pdf_buffer.py#L292

Can you send PR? Thanks ;)
