### ISSUE TITLE
fitz module installed similar package (not from mupdf)

### ISSUE THREAD

**Issue by sawyerzheng** [emacs-eaf/eaf-pdf-viewer#87]
Error： `install-eaf.py` will use `pip install fitz` to install module from https://github.com/kastman/fitz, instead of fitz from mupdf.

-----

My successfull  manual fixing : 
``` sh
pip uninstall fitz
pip install pymupdf
```

**Comment by manateelazycat** [comment]
You mean we need remove fitz from install-eaf.py ?

**Comment by sawyerzheng** [comment]
Yes.

Because the fitz module we want to install is already packaged with pymupdf(actually itself is fitz module). 

the [pypa fitz](https://pypi.org/project/fitz/) module is not the one we want, just a module with similar name.

**Comment by manateelazycat** [comment]
Done, thanks for report. ;)

**Comment by MatthewZMD** [comment]
Fitz was added because of this issue:

https://github.com/emacs-eaf/emacs-application-framework/issues/1022
