### ISSUE TITLE
如果要把本项目改造成一个独立的PDF阅读器，请问该从哪里改起？

### ISSUE THREAD

**Issue by redstoneleo** [emacs-eaf/eaf-pdf-viewer#90]
如果要把本项目改造成一个独立的PDF阅读器，请问该从哪里改起？能否指教一二，谢谢！

**Comment by manateelazycat** [comment]
自己看源码吧， 和Emacs关联太多， 没有时间讲解。

如果自己PyQt 过硬， 直接基于 mupdf 开发更快。
