### ISSUE TITLE
页面跳转不准确

### ISSUE THREAD

**Issue by czqhurricnae** [emacs-eaf/eaf-pdf-viewer#97]
**Describe the bug**
不论是使用快捷键 p，输入跳转所需页面数字，还是 pdfgrep 预览调用，都不能准确跳转到目标页面。

`eaf-pdf-jump-to-page`。

**Versions (please complete the following info):**
eaf-pdf-viewer 版本：f9a96b5 master origin/master grafted New render translate code is wrong, revert to previous version.

**Screenshots**
![截屏2022-12-22 23 34 10](https://user-images.githubusercontent.com/20676402/209170793-3e357fce-e18b-44e3-b3eb-ce5fd527ba73.png)

**Comment by manateelazycat** [comment]
pdfgrep找的是图书索引，EAF目前是绝对索引。

还没有想到好的办法去处理，先放放

**Comment by czqhurricnae** [comment]
![截屏2022-12-23 16 58 14](https://user-images.githubusercontent.com/20676402/209305613-11636f04-e177-46f4-96e2-ea8c2f643439.png)


如上图，总页数显示是 307，无论是一页一页的滚动浏览，在第 304 页按 j 就无法继续翻页了。

使用快捷键 G 试图跳到最后一页，也只能跳到 304.。

但是很明显文档还没到结尾处。

测试文件可以在此处下载获得：[大型飞机公共航空运输承运人运行合格审定规则.pdf](http://www.caac.gov.cn/XXGK/XXGK/MHGZ/202104/P020210506533065323228.pdf)

**Comment by manateelazycat** [comment]
更新看看吧。

**Comment by czqhurricnae** [comment]
可以滚动到末页了，但是页数还是有问题。实际的页数总是比输入的多一页。

**Comment by manateelazycat** [comment]
> 可以滚动到末页了，但是页数还是有问题。实际的页数总是比输入的多一页。

页数问题先放着吧

**Comment by manateelazycat** [comment]
应该都修复了。
