### ISSUE TITLE
提示“Failed to reload PDF file!”

### ISSUE THREAD

**Issue by yqu212** [emacs-eaf/eaf-pdf-viewer#98]
eaf-pdf-viewer最近总是提示“Failed to reload PDF file!”,定位到[eaf_pdf_document.py的100行](https://github.com/emacs-eaf/eaf-pdf-viewer/blob/b5d4d31fa74eb14e66dc11b0e383691e9351e21b/eaf_pdf_document.py#L100)，去掉try .. catch之后\*eaf\* buffer里面显示

> RuntimeError: wrapped C/C++ object of type PdfViewerWidget has been deleted

 - Distro and DE/WM: Manjaro and i3wm
 - Versions of Dependencies:
 - M-x emacs-version: GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12

**Comment by manateelazycat** [comment]
@yqu212 这个问题我偶尔也遇到， 但是没法稳定重现， 大概率是 https://github.com/emacs-eaf/eaf-pdf-viewer/commit/32b04ac0a209fdc7f62a6acab3a9832a1ebfd926 这个补丁引起的。

@smallzhan 能帮忙看一下吗？

**Comment by yqu212** [comment]
我这边只要预览LaTeX编译的PDF就能看到这个问题。PDF的重新加载实际上是正常的。

**Comment by manateelazycat** [comment]
> 我这边只要预览LaTeX编译的PDF就能看到这个问题。PDF的重新加载实际上是正常的。

我不用LaTeX, 暂时帮不了你

**Comment by yqu212** [comment]
那我再看看吧。现在把报错给注释了，不影响使用。
