### ISSUE TITLE
请问选择文本的快捷键是什么？

### ISSUE THREAD

**Issue by nigo81** [emacs-eaf/eaf-pdf-viewer#99]
使用eaf-pdf-viewer是为了追求全键盘，README中介绍了复制文本是 `M-w`，但是选择文本我还是只能用鼠标去选择。
请问是否能纯键盘去选择文本？
非常感谢您的插件！

**Comment by manateelazycat** [comment]
现在还不支持键盘选择

**Comment by nigo81** [comment]
> 但是可以导出文本或者OCR后用emacs编辑

好的，再次感谢。
